name: Push to root folder on server
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        run: |
           cd /var/www/html/test/ && git pull
